data:
  raw_path: "data/raw"
  processed_path: "data/processed"
  dvc_remote: "s3://mybucket"

airflow:
  executor: "LocalExecutor"
  dags_folder: "/opt/airflow/dags"

services:
  minio:
    url: "http://localhost:9000"
    access_key: "minioadmin"
    secret_key: "minioadmin"
