apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  labels:
    app: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
      - name: airflow
        image: apache/airflow:2.6.2
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: "LocalExecutor"
        args: [ "webserver" ]
      volumes:
      - name: dags
        emptyDir: {}
