apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openmetadata-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: openmetadata
  labels:
    app: openmetadata
spec:
  ports:
  - port: 8585
    targetPort: 8585
  selector:
    app: openmetadata
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmetadata
  labels:
    app: openmetadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmetadata
  template:
    metadata:
      labels:
        app: openmetadata
    spec:
      containers:
      - name: openmetadata
        image: openmetadata/server:latest
        ports:
        - containerPort: 8585
        env:
        # Database configuration
        - name: DATABASE_HOST
          value: "localhost" # Update for your database location
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USERNAME
          value: "openmetadata_user"
        - name: DATABASE_PASSWORD
          value: "openmetadata_password"
        - name: DATABASE_NAME
          value: "openmetadata_db"
        - name: DATABASE_SCHEMA
          value: "openmetadata"
        - name: DATABASE_DRIVER
          value: "postgres"

        # Metadata service configuration
        - name: METADATA_SERVER_CONFIG
          value: "http://localhost:8585/api"

        # MinIO storage configuration
        - name: MINIO_ENDPOINT
          value: "http://minio:9000"
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        volumeMounts:
        - name: openmetadata-data
          mountPath: /data
      volumes:
      - name: openmetadata-data
        persistentVolumeClaim:
          claimName: openmetadata-data
