metadataServerConfig:
  apiEndpoint: http://localhost:8585/api # OpenMetadata API endpoint
  authProvider: no-auth # Authentication type (use 'basic' for credentials)
  enableVersionValidation: false # Skip version validation if necessary

pipelineService:
  name: fraud-detection-mlops # Name of your service in OpenMetadata
  type: airflow # Workflow orchestrator type (e.g., Airflow)
  airflowConfig:
    # Airflow-specific settings
    airflowEndpoint: http://localhost:8080

storageService:
  name: fraud-detection-minio # Name of the MinIO service
  type: s3 # Use S3-compatible APIs
  connection:
    config:
      awsConfig:
        awsAccessKeyId: minioadmin # MinIO Access Key
        awsSecretAccessKey: minioadmin # MinIO Secret Key
        awsRegion: us-east-1 # Default region
        endpointURL: http://localhost:9000 # MinIO endpoint
