---
source:
  type: s3
  serviceName: fraud-detection-minio
  serviceConnection:
    config:
      type: S3
      bucketName: fraud-detection-data
      awsConfig:
        awsAccessKeyId: minioadmin
        awsSecretAccessKey: minioadmin
        endpointURL: http://localhost:9000
workflowConfig:
  loggerLevel: INFO
  openMetadataServerConfig:
    hostPort: http://localhost:8585
    authProvider: no-auth
metadataServerConfig:
  apiEndpoint: http://localhost:8585/api
  authProvider: no-auth
pipelineService:
  name: fraud-detection-mlops
  type: airflow
  airflowConfig:
    airflowEndpoint: http://localhost:8080
storageService:
  name: fraud-detection-minio
  type: s3
