name: Deploy Coverage to Pages

on:
  # Trigger workflow on pushes to the default branch
  push:
    branches: ["main"]

  # Allow manual trigger of the workflow
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Install Python dependencies to generate the coverage report
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests and generate the coverage report
      - name: Run tests and generate coverage report
        run: |
          pytest --cov=src --cov-report=html tests/

      # Upload the coverage report artifact for deployment
      - name: Upload coverage artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: htmlcov

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
